name: carnd-advdl-odlab
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - pip
    - python==3.7.5
    - numpy==1.17.3
    - matplotlib==3.1.1
    - jupyter==1.0.0
    - pillow==6.2.1
    - scipy==1.3.1
    - ffmpeg==4.2
    - imageio==2.6.1
    - pip:
        - moviepy==1.0.1
        - tensorflow==1.15
